//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipIT
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class SHIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIPMENT()
        {

            //this.EMPLOYEEs = new ObservableCollection<EMPLOYEE>();

            //new code
            this.Shipper = new EMPLOYEE();
            this.Receiver = new EMPLOYEE();
        }
    
        public int ShipmentId { get; set; }
        public System.DateTime DateShipped { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ObservableCollection<EMPLOYEE> EMPLOYEEs { get; set; }

        //new code
        public virtual EMPLOYEE Shipper { get; set; }
        public virtual EMPLOYEE Receiver { get; set; }
    }
}
